### ISSUE TITLE
Incorrect official project link

### ISSUE THREAD

**Issue by YashwanthAsh** [SoftwareEngineeringToolDemos/ICSE-2012-CTD#10]
Paper is about CTD technique which is developed by IBM and used in IBM FOCUS. 
Read me should have official IBM FOCUS link but not a third party tool which uses IBM FOCUS internally.

Even for the Fittest tool official link is http://crest.cs.ucl.ac.uk/fittest/index.html

**Comment by nplimaye** [comment]
IBM FOCUS link added
