### ISSUE TITLE
Contradiction: Repository is created for Fittest where as paper is about CTD

### ISSUE THREAD

**Issue by YashwanthAsh** [SoftwareEngineeringToolDemos/ICSE-2012-CTD#15]
Paper talks about CTD technique designed by IBM which is used in IBM FOCUS.
Repository should be created for IBM FOCUS instead repository is created for FITTEST, a tool which internally uses IBM FOCUS for CTD technique. FITTEST doesn't have its own implementation for CTD.

**Comment by nplimaye** [comment]
made the necessary changes
